package version

import (
	"fmt"
	"time"
)

type Version struct {
}

func NewVersion() *Version {
	return &Version{}
}

func (*Version) Name(string, string) string {
	return "version.go"
}

func (*Version) Gen(pkgName string, fileName string) string {
	version := time.Now().Format("20060102150405")
	content := fmt.Sprintf(`// Code generated by go generate; DO NOT EDIT.
package %s  
const BUILDTIME = "%s"
`, pkgName, version)
	return content
}
